# Generated by Django 4.0.2 on 2022-02-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_neworder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neworder',
            name='name',
        ),
        migrations.AddField(
            model_name='neworder',
            name='items',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
