# Generated by Django 4.0.2 on 2022-02-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_neworder_name_neworder_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neworder',
            old_name='items',
            new_name='item',
        ),
    ]
