# Generated by Django 4.0.2 on 2022-02-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_rename_items_neworder_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewOrder',
            new_name='OrderList',
        ),
    ]
