# Generated by Django 4.0.2 on 2022-02-24 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_rename_neworder_orderlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='item',
        ),
    ]
