# Generated by Django 4.0.2 on 2022-02-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_remove_orderlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='items',
            field=models.JSONField(null=True),
        ),
    ]
