# Generated by Django 4.0.2 on 2022-02-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_orderlist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='customer_name',
        ),
    ]
